development: &default
  adapter: mysql2
  database: crowdbus-web-development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  socket: /tmp/mysql.sock
  username: root

test:
  <<: *default
  database: crowdbus-web-test

# production:
#   <<: *default
#   database: crowdtrack
