development: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: crowdtrack-development
  pool: 5
  username: crowdtrack
  password: 1234

test:
  <<: *default
  database: crowdtrack-test

production:
  <<: *default
  database: crowdtrack

